# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define() do

  create_table "blogcommunityfields", :force => true do |t|
    t.column "blogId", :integer,               :default => 0,  :null => false
    t.column "name",   :string,  :limit => 50, :default => "", :null => false
    t.column "value",  :string,                :default => "", :null => false
  end

  add_index "blogcommunityfields", ["blogId", "name", "value"], :name => "blogId", :unique => true
  add_index "blogcommunityfields", ["blogId"], :name => "blog_com_flds_id"
  add_index "blogcommunityfields", ["name"], :name => "blog_com_flds_name"

  create_table "bloglinks", :force => true do |t|
    t.column "blogId",         :integer
    t.column "urlHashCode",    :integer,               :default => 0,  :null => false
    t.column "lastAccessTime", :integer, :limit => 20, :default => -1, :null => false
  end

  add_index "bloglinks", ["urlHashCode"], :name => "urlHashCode", :unique => true
  add_index "bloglinks", ["blogId"], :name => "blog_id"

  create_table "blogs", :force => true do |t|
    t.column "title",               :string
    t.column "author",              :string
    t.column "description",         :text
    t.column "htmlUrl",             :text
    t.column "dataUrl",             :text
    t.column "inboundLinks",        :integer,               :default => -1,    :null => false
    t.column "rank",                :integer,               :default => -1,    :null => false
    t.column "category",            :string
    t.column "location",            :string
    t.column "status",              :integer, :limit => 4,  :default => 0,     :null => false
    t.column "lastAccessTime",      :integer, :limit => 20, :default => -1,    :null => false
    t.column "lastUpdateTime",      :integer, :limit => 20, :default => -1,    :null => false
    t.column "incompleteDiscovery", :boolean,               :default => false, :null => false
  end

  add_index "blogs", ["lastAccessTime"], :name => "blog_access_time"
  add_index "blogs", ["lastUpdateTime"], :name => "blog_update_time"

  create_table "channels", :force => true do |t|
    t.column "title",      :string,  :limit => 100, :default => "", :null => false
    t.column "htmlUrl",    :text
    t.column "xmlUrl",     :text,                   :default => "", :null => false
    t.column "xmlUrlHash", :integer,                :default => 0,  :null => false
  end

  add_index "channels", ["xmlUrlHash"], :name => "xml_url_hash"

  create_table "clienterrors", :force => true do |t|
    t.column "message", :string,                :default => "", :null => false
    t.column "details", :text
    t.column "time",    :integer, :limit => 20, :default => 0,  :null => false
    t.column "version", :string,  :limit => 8,  :default => "", :null => false
  end

  add_index "clienterrors", ["time"], :name => "client_errors_time"
  add_index "clienterrors", ["message"], :name => "client_errors_message"
  add_index "clienterrors", ["version"], :name => "client_errors_version"

  create_table "events", :force => true do |t|
    t.column "user_id",     :integer
    t.column "created_at",  :datetime,                               :null => false
    t.column "event_type",  :integer,                 :default => 0, :null => false
    t.column "description", :string,   :limit => 250
  end

  add_index "events", ["user_id"], :name => "user_id"
  add_index "events", ["created_at"], :name => "created_at"
  add_index "events", ["event_type"], :name => "event_type"

  create_table "features", :force => true do |t|
    t.column "name",               :string,  :limit => 50,  :default => "",    :null => false
    t.column "title",              :string,  :limit => 50,  :default => "",    :null => false
    t.column "description",        :text
    t.column "format_description", :text
    t.column "default_value",      :string,  :limit => 200
    t.column "hidden",             :boolean,                :default => false, :null => false
  end

  add_index "features", ["name"], :name => "name", :unique => true

  create_table "feedbackmessages", :force => true do |t|
    t.column "message", :text,                  :default => "", :null => false
    t.column "time",    :integer, :limit => 20, :default => 0,  :null => false
  end

  add_index "feedbackmessages", ["time"], :name => "feedback_messages_time"

  create_table "installations", :id => false, :force => true do |t|
    t.column "ID",               :integer,  :limit => 16,                :null => false
    t.column "InstallationDate", :datetime,                              :null => false
    t.column "Version",          :string,   :limit => 10
    t.column "Runs",             :integer,  :limit => 6,  :default => 0, :null => false
    t.column "OS",               :string,   :limit => 50
    t.column "JavaVersion",      :string,   :limit => 50
    t.column "UserID",           :integer
  end

  add_index "installations", ["UserID"], :name => "installations_userid"

  create_table "messages", :force => true do |t|
    t.column "title",    :string,                :default => "", :null => false
    t.column "text",     :text,                  :default => "", :null => false
    t.column "version",  :string,  :limit => 10
    t.column "priority", :integer,               :default => 1,  :null => false
    t.column "mtype",    :integer,               :default => 1,  :null => false
  end

  add_index "messages", ["version"], :name => "messages_version"

  create_table "plans", :force => true do |t|
    t.column "name",          :string,  :limit => 50, :default => "",    :null => false
    t.column "description",   :text
    t.column "price",         :float,                 :default => 0.0,   :null => false
    t.column "period_months", :integer,               :default => 0,     :null => false
    t.column "serial",        :integer,               :default => 0,     :null => false
    t.column "hidden",        :boolean,               :default => false, :null => false
  end

  add_index "plans", ["name"], :name => "name", :unique => true
  add_index "plans", ["price"], :name => "price"

  create_table "plans_features", :id => false, :force => true do |t|
    t.column "plan_id",    :integer,                :default => 0, :null => false
    t.column "feature_id", :integer,                :default => 0, :null => false
    t.column "value",      :string,  :limit => 200
  end

  add_index "plans_features", ["plan_id"], :name => "plan_id"
  add_index "plans_features", ["feature_id"], :name => "feature_id"

  create_table "readinglistvisits", :id => false, :force => true do |t|
    t.column "userId",          :integer,                :default => 0,  :null => false
    t.column "title",           :string,   :limit => 50, :default => "", :null => false
    t.column "accessDate",      :datetime,                               :null => false
    t.column "clientIP",        :integer,                :default => 0,  :null => false
    t.column "clientUserAgent", :string
  end

  add_index "readinglistvisits", ["userId"], :name => "userId"

  create_table "runs", :id => false, :force => true do |t|
    t.column "InstallationID", :integer,  :limit => 16, :default => 0, :null => false
    t.column "RunDate",        :datetime,                              :null => false
  end

  add_index "runs", ["InstallationID"], :name => "installation_id"

  create_table "userchannels", :force => true do |t|
    t.column "userGuideId",        :integer,                :default => 0,     :null => false
    t.column "channelId",          :integer,                :default => 0,     :null => false
    t.column "userReadingListId",  :integer
    t.column "rating",             :integer,                :default => -1,    :null => false
    t.column "indx",               :integer,                :default => 0,     :null => false
    t.column "readArticlesKeys",   :text
    t.column "pinnedArticlesKeys", :text
    t.column "purgeLimit",         :integer,                :default => -1,    :null => false
    t.column "customTitle",        :string,  :limit => 100
    t.column "customCreator",      :string,  :limit => 100
    t.column "customDescription",  :text
    t.column "tags",               :text
    t.column "tagsExtended",       :text
    t.column "tagsDescription",    :text
    t.column "disabled",           :boolean,                :default => false, :null => false
    t.column "viewType",           :integer,                :default => 0,     :null => false
    t.column "viewModeEnabled",    :boolean,                :default => false, :null => false
    t.column "viewMode",           :integer,                :default => -1,    :null => false
    t.column "ascendingSorting",   :boolean
    t.column "updatePeriod",       :integer, :limit => 20,  :default => -1,    :null => false
  end

  add_index "userchannels", ["userGuideId", "channelId"], :name => "userGuideId", :unique => true
  add_index "userchannels", ["channelId"], :name => "channel_id"
  add_index "userchannels", ["userReadingListId"], :name => "user_reading_list_id"

  create_table "userguides", :force => true do |t|
    t.column "userId",               :integer,                :default => 0,     :null => false
    t.column "title",                :string,  :limit => 100, :default => "",    :null => false
    t.column "iconKey",              :string,  :limit => 50
    t.column "indx",                 :integer,                :default => 0,     :null => false
    t.column "publishingEnabled",    :boolean,                :default => false, :null => false
    t.column "publishingTitle",      :string,  :limit => 100
    t.column "publishingTags",       :text
    t.column "publishingPublic",     :boolean,                :default => false, :null => false
    t.column "publishingRating",     :integer,                :default => 0,     :null => false
    t.column "autoFeedsDiscovery",   :boolean,                :default => false, :null => false
    t.column "notificationsAllowed", :boolean,                :default => true,  :null => false
  end

  add_index "userguides", ["userId", "indx"], :name => "userId", :unique => true

  create_table "userpreferences", :force => true do |t|
    t.column "userId", :integer,                :default => 0,  :null => false
    t.column "name",   :string,  :limit => 100, :default => "", :null => false
    t.column "value",  :text
  end

  add_index "userpreferences", ["userId", "name"], :name => "userId", :unique => true

  create_table "userqueryfeeds", :force => true do |t|
    t.column "userGuideId",        :integer,                :default => 0,     :null => false
    t.column "indx",               :integer,                :default => 0,     :null => false
    t.column "title",              :string,  :limit => 250, :default => "",    :null => false
    t.column "queryType",          :integer,                :default => 0,     :null => false
    t.column "queryParam",         :text
    t.column "rating",             :integer,                :default => -1,    :null => false
    t.column "purgeLimit",         :integer,                :default => -1,    :null => false
    t.column "readArticlesKeys",   :text
    t.column "pinnedArticlesKeys", :text
    t.column "viewType",           :integer,                :default => 0,     :null => false
    t.column "viewModeEnabled",    :boolean,                :default => false, :null => false
    t.column "viewMode",           :integer,                :default => -1,    :null => false
    t.column "dedupEnabled",       :boolean,                :default => false, :null => false
    t.column "dedupFrom",          :integer,                :default => -1,    :null => false
    t.column "dedupTo",            :integer,                :default => -1,    :null => false
    t.column "ascendingSorting",   :boolean
    t.column "updatePeriod",       :integer, :limit => 20,  :default => -1,    :null => false
  end

  add_index "userqueryfeeds", ["userGuideId", "indx"], :name => "userGuideId", :unique => true
  add_index "userqueryfeeds", ["userGuideId"], :name => "user_guide_id"

  create_table "userreadinglists", :force => true do |t|
    t.column "userGuideId", :integer,                :default => 0,  :null => false
    t.column "title",       :string,  :limit => 100, :default => "", :null => false
    t.column "xmlUrl",      :text,                   :default => "", :null => false
  end

  add_index "userreadinglists", ["userGuideId"], :name => "rl_user_guide_id"

  create_table "users", :force => true do |t|
    t.column "fullName",           :string,   :limit => 50, :default => "",      :null => false
    t.column "email",              :string,   :limit => 50, :default => "",      :null => false
    t.column "password",           :string,   :limit => 25, :default => "",      :null => false
    t.column "activated",          :boolean,                :default => false,   :null => false
    t.column "registrationDate",   :datetime,                                    :null => false
    t.column "locale",             :string,   :limit => 5,  :default => "en_US", :null => false
    t.column "notifyOnUpdates",    :boolean,                :default => false,   :null => false
    t.column "lastSyncTime",       :datetime
    t.column "plan_id",            :integer,                :default => 1,       :null => false
    t.column "plan_period_months", :integer
    t.column "plan_price",         :float
    t.column "plan_exp_date",      :datetime
    t.column "plan_is_trial",      :boolean,                :default => false,   :null => false
    t.column "plan_is_trial_used", :boolean,                :default => false,   :null => false
    t.column "q_hear",             :string,   :limit => 25
    t.column "q_occupation",       :string,   :limit => 25
    t.column "pp_subid",           :string,   :limit => 50
    t.column "pp_payments",        :integer
    t.column "pp_since",           :datetime
    t.column "pp_cancelled",       :datetime
    t.column "apikey",             :string,   :limit => 36, :default => "",      :null => false
  end

  add_index "users", ["apikey"], :name => "apikey", :unique => true
  add_index "users", ["email"], :name => "email", :unique => true
  add_index "users", ["plan_id"], :name => "plan_id"
  add_index "users", ["apikey"], :name => "apikey_2"

  create_table "usersearchfeeds", :force => true do |t|
    t.column "userGuideId",      :integer,                :default => 0,     :null => false
    t.column "indx",             :integer,                :default => 0,     :null => false
    t.column "title",            :string,  :limit => 250, :default => "",    :null => false
    t.column "query",            :text
    t.column "rating",           :integer,                :default => -1,    :null => false
    t.column "purgeLimit",       :integer,                :default => -1,    :null => false
    t.column "viewType",         :integer,                :default => 0,     :null => false
    t.column "viewModeEnabled",  :boolean,                :default => false, :null => false
    t.column "viewMode",         :integer,                :default => -1,    :null => false
    t.column "dedupEnabled",     :boolean,                :default => false, :null => false
    t.column "dedupFrom",        :integer,                :default => -1,    :null => false
    t.column "dedupTo",          :integer,                :default => -1,    :null => false
    t.column "ascendingSorting", :boolean
  end

  add_index "usersearchfeeds", ["userGuideId", "indx"], :name => "userGuideId", :unique => true
  add_index "usersearchfeeds", ["userGuideId"], :name => "sf_user_guide_id"

  create_table "usersharedtags", :id => false, :force => true do |t|
    t.column "userId",      :integer, :default => 0,  :null => false
    t.column "url",         :text,    :default => "", :null => false
    t.column "feed",        :boolean
    t.column "tags",        :text,    :default => "", :null => false
    t.column "description", :text,    :default => "", :null => false
    t.column "extended",    :text
  end

  add_index "usersharedtags", ["userId"], :name => "usf_user_id"

  create_table "usersyncs", :id => false, :force => true do |t|
    t.column "userId",   :integer,               :default => 0,     :null => false
    t.column "synctime", :integer, :limit => 20, :default => 0,     :null => false
    t.column "store",    :boolean,               :default => false, :null => false
  end

  add_index "usersyncs", ["userId"], :name => "usersyncs_userid"
  add_index "usersyncs", ["store"], :name => "usersyncs_store"

  create_table "versionchanges", :force => true do |t|
    t.column "versionId", :integer, :default => 0,  :null => false
    t.column "type",      :integer, :default => 0,  :null => false
    t.column "details",   :text,    :default => "", :null => false
  end

  add_index "versionchanges", ["versionId"], :name => "version_changes_versionid"

  create_table "versions", :force => true do |t|
    t.column "version",     :string,  :limit => 10, :default => "", :null => false
    t.column "releaseTime", :integer, :limit => 20, :default => 0,  :null => false
    t.column "production",  :boolean
  end

end
